== JDBC DataSource configuration

The Holon platform provides an API to create and configure JDBC `DataSource` instances using a set of configuration properties.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jdbc</groupId>
<artifactId>holon-jdbc</artifactId>
<version>{revnumber}</version>
----

[[DataSourceBuilder]]
=== DataSource builder

The link:{apidir}/com/holonplatform/jdbc/DataSourceBuilder.html[DataSourceBuilder^] interface can be used to build `DataSource` instances using a `DataSourceConfigProperties` instance as configuration property source, using the `build(DataSourceConfigProperties configurationProperties)` method.

The default `DataSourceBuilder` implementation, which can be obtained through the `create()` interface static methods, relies on the `type` configuration property to define the concrete `DataSource` instance to create and configure.

The following types are supported by default:

* `com.holonplatform.jdbc.BasicDataSource`: Create `BasicDataSource` instances, to be used typically for testing purposes. It is a simple `DataSource` implementation, using the `java.sql.DriverManager` class and returning a new
`java.sql.Connection` from every `getConnection` call.

* `com.zaxxer.hikari.HikariDataSource`: Create https://github.com/brettwooldridge/HikariCP[HikariCP] connection pooling `DataSource` instances. The _HikariCP_ library dependency must be available in classpath. All default configuration properties are supported, and additional Hikari-specific configuration properties can be specified using the `hikari` prefix before the actual property name, for example: `holon.datasource.*hikari*.connectionTimeout`.

* `org.apache.commons.dbcp2.BasicDataSource`: Create http://commons.apache.org/proper/commons-dbcp/[Apache Commons DBCP 2] connection pooling `DataSource` instances. The _DBCP 2_ library dependency must be available in classpath. All default configuration properties are supported, and additional DBCP-specific configuration properties can be specified using the `dbcp` prefix before the actual property name, for example: `holon.datasource.*dbcp*.maxWaitMillis`.

* `org.apache.tomcat.jdbc.pool.DataSource`: Create https://tomcat.apache.org/tomcat-8.5-doc/jdbc-pool.html[Tomcat JDBC] connection pooling `DataSource` instances. The _tomcat-jdbc_ library dependency must be available in classpath. All default configuration properties are supported, and additional Tomcat-specific configuration properties can be specified using the `tomcat` prefix before the actual property name, for example: `holon.datasource.*tomcat*.maxAge`.

* `JNDI`: Obtain a `DataSource` using *JNDI*. The `jndi-name` configuration property is required to specify the JNDI name to which the `DataSource` is bound in the JNDI context.

==== Default DataSource type selection strategy

If the `type` configuration property is not specified, the default DataSource `type` selection strategy adopted by the `DataSourceBuilder` is defined as follows:

. If the https://github.com/brettwooldridge/HikariCP[HikariCP] dependecy is present in classpath, the `com.zaxxer.hikari.HikariDataSource` type will be used;
. If the http://commons.apache.org/proper/commons-dbcp/[Apache Commons DBCP 2] dependecy is present in classpath, the `org.apache.commons.dbcp2.BasicDataSource` type will be used;
. If the https://tomcat.apache.org/tomcat-8.5-doc/jdbc-pool.html[Tomcat JDBC] dependecy is present in classpath, the `org.apache.tomcat.jdbc.pool.DataSource` type will be used;
. Otherwise, the `com.holonplatform.jdbc.BasicDataSource` type is used as fallback.

For example, using the following configuration properties file:

[source, text]
.datasource.properties
----
holon.datasource.url=jdbc:h2:mem:testdb
holon.datasource.username=sa
holon.datasource.password=
----

The `DataSourceBuilder` can be used as follows, creating a DataSource of a type determined according to the default type selection strategy:

[source, java]
----
include::{examplesdir}/com/holonplatform/jdbc/examples/ExampleJdbc.java[tag=builder,indent=0]
----
<1> Create a configuration property set using the `datasource.properties` as property source
<2> Build a `DataSource` instance according to given configuration properties

To specify the `DataSource` type to create, the `type` property can be used. For example, to use https://github.com/brettwooldridge/HikariCP[HikariCP] pooling DataSource:

[source, text]
.datasource2.properties
----
holon.datasource.url=jdbc:h2:mem:testdb
holon.datasource.username=sa
holon.datasource.password=

holon.datasource.type=com.zaxxer.hikari.HikariDataSource
----

The `DataSourceBuilder` is used the same as before:

[source, java]
----
include::{examplesdir}/com/holonplatform/jdbc/examples/ExampleJdbc.java[tag=builder2,indent=0]
----
<1> Create a configuration property set using the `datasource2.properties` as property source
<2> Build a `DataSource` instance according to given configuration properties, which will be an `HikariDataSource` instance

WARNING: In order to create `HikariDataSource` instances, the HikariCP library must be present in classpath. Similarly, to create Tomcat JDBC pooling DataSources, the Tomcat JDBC library must be present in classpath.

==== DataSourceFactory

The default `DataSourceBuilder` implementation delegates `DataSource` instances creation to  link:{apidir}/com/holonplatform/jdbc/DataSourceFactory.html[DataSourceFactory^] interface implementation, each of them bound to a single `DataSource` *type* name, which must be registered in the `DataSourceBuilder`.

A `DataSourceFactory` can be used to provide additional `DataSource` types support or to replace a default type creation strategy with a new one. The `DataSource` type name to which the `DataSourceFactory` is bound is provided by the `getDataSourceType()` interface method.

The registration of a `DataSourceFactory` can be accomplished in two ways:

* *Direct registration*: A `DataSourceFactory` instance can directly registered in a `DataSourceBuilder` instance using the `registerFactory(DataSourceFactory factory)` method. Any previous binding with given type will be replaced by the given factory.

* *Extension services*: The default Java `ServiceLoader` extensions can be used, providing a `com.holonplatform.jdbc.DataSourceFactory` file under a `META-INF/services` folder in classpath, in which to specify the fully qualified name of the `DataSourceFactory` implementation. This way, the factory is automatically registered when the builder instance is initialized.

==== DataSourcePostProcessor

The link:{apidir}/com/holonplatform/jdbc/DataSourcePostProcessor.html[DataSourcePostProcessor^] interface can be used to perform additional initialization and configuration on a {@link DataSource} instance created using the `DataSourceBuilder`. The `postProcessDataSource(...)` method is called just after the creation of any DataSource instance. In order to activate a `DataSourcePostProcessor`, it must be registered in the `DataSourceBuilder` instance. The order with which the post processors are invoked reflect their registration order.

The registration of a `DataSourcePostProcessor` can be accomplished in two ways:

* *Direct registration*: A `DataSourcePostProcessor` instance can directly registered in a `DataSourceBuilder` instance using the `registerPostProcessor(DataSourcePostProcessor postProcessor)` method.

* *Extension services*: The default Java `ServiceLoader` extensions can be used, providing a `com.holonplatform.jdbc.DataSourcePostProcessor` file under a `META-INF/services` folder in classpath, in which to specify the fully qualified name of the `DataSourcePostProcessor` implementation. This way, the post processor is automatically registered when the builder instance is initialized.

[[DataSourceConfigProperties]]
=== DataSource configuration properties

The available `DataSource` configuration properties are collected and represented by the link:{apidir}/com/holonplatform/jdbc/DataSourceConfigProperties.html[DataSourceConfigProperties^] interface, extending a default `ConfigPropertySet` bound to the property name prefix *holon.datasource*.

The available configuration properties are listed below:

.DataSource configuration properties
|===
|Name |Type |Meaning

|_holon.datasource._ *type*
|String
|DataSource type name. 

|_holon.datasource._ *driver-class-name*
|String
|The JDBC Driver class name to use. If not specified, the default DataSource builder tries to auto-detect it form the connection URL.

| _holon.datasource._ *url*
|String
|JDBC connection url

|_holon.datasource._ *username*
|String
|JDBC connection username

|_holon.datasource._ *password*
|String
|JDBC connection password

|_holon.datasource._ *platform*
|`DatabasePlatform` enumeration
|Database platform to which the DataSource is connected. If not specified, the DataSource builder tries to auto-detect it form the connection URL.

|_holon.datasource._ *auto-commit*
|Boolean (`true` / `false`)
|Enable/Disable auto-commit for the JDBC driver

|_holon.datasource._ *max-pool-size*
|Integer number
|For connection pooling DataSource types, configure the minimum connection pool size

|_holon.datasource._ *min-pool-size*
|Integer number
|For connection pooling DataSource types, configure the maximum connection pool size

|_holon.datasource._ *validation-query*
|String
|For connection pooling DataSource types the query to use to validate the connections in the pool

|_holon.datasource._ *jndi-name*
|String
|_JNDI_ lookup name for `JNDI` DataSource retrieval strategy
|===

The `DataSourceConfigProperties` can be loaded from a number a sources using the default `ConfigPropertySet` builder interface:

[source, java]
----
include::{examplesdir}/com/holonplatform/jdbc/examples/ExampleJdbc.java[tag=configuration,indent=0]
----
<1> Read the configuration properties from _default_ property sources (i.e. the `holon.properties` file)
<2> Read the configuration properties from `System` properties
<3> Read the configuration properties from a `Properties` instance
<4> Read the configuration properties from the `datasource.properties` file
<5> Read the configuration properties from the `datasource.properties` `InputStream`

=== Multiple DataSource configuration

When a multiple `DataSource` configuration is required and properties are read from the same source, a _data context id_ can be used to discern one `DataSource` configuration property set form another.

From the property source point of view, the _data context id_ is used as a *suffix* after the configuration property set name (`holon.datasource`) and before the specific property name.

For example, suppose we have a configuration property set for two different data sources as follows:

[source, text]
----
holon.datasource.one.url=jdbc:h2:mem:testdb1
holon.datasource.one.username=sa

holon.datasource.two.url=jdbc:h2:mem:testdb2
holon.datasource.two.username=sa
----

To build two DataSources, one bound to the `one` configuration property set and the other bound to the `two` configuration property set, the `DataSourceConfigProperties` can be obtained as follows, specifying the _data context id_ when obtaining the builder:

[source, java]
----
include::{examplesdir}/com/holonplatform/jdbc/examples/ExampleJdbc.java[tag=configuration2,indent=0]
----

=== BasicDataSource

A link:{apidir}/com/holonplatform/jdbc/BasicDataSource.html[BasicDataSource^] is provided to directly use a simple, standard `javax.sql.DataSource` implementation.

The `BasicDataSource` uses the `java.sql.DriverManager` class and returns a new `java.sql.Connection` from every `getConnection()` call.

For this reason, can be useful for test or standalone environments outside J2EE containers.

A fluent builder is provided to create and configure a `BasicDataSource` instance:

[source, java]
----
include::{examplesdir}/com/holonplatform/jdbc/examples/ExampleBasicDataSource.java[tag=basic,indent=0]
----
<1> Build a `BasicDataSource` providing driver class name
<2> Build a `BasicDataSource` using the `DatabasePlatform` enumeration to obtain the driver class name
