= Holon Platform JDBC Module - Reference manual
:description: Holon platform JDBC module reference documentation. \
The JDBC module provides Java DataBase Connectivity (JDBC) support, dealing with DataSource configuration and management in single or multiple persistence source enviroments and DataSource configuration in a Spring context, including the Spring Boot support.
:revnumber: {project-version}
:apidir: ../api/holon-jdbc
:linkattrs:
:sectnums:
:nofooter:
:toc: left
:toclevels: 3

Copyright © 2016-2017

_Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically._

== Introduction

The Holon Platform *JDBC* module provides base JDBC support to the Holon platform, dealing with `javax.sql.DataSource` configuration and providing a _multi-tenant_ DataSource implementation. 

Futhermore, the module provides integration with the *Spring* framework relatively to `DataSource` configuration and `DataSource` auto-configuration facilities using *Spring Boot*.

=== Sources and contributions

The Holon Platform *JDBC* module source code is available from the GitHub repository link:https://github.com/holon-platform/holon-jdbc[https://github.com/holon-platform/holon-jdbc^].

See the repository `README` file for information about:

* The source code structure.
* How to build the module artifacts from sources.
* Where to find the code examples.
* How to contribute to the module development.

== Obtaining the artifacts

The Holon Platform uses https://maven.apache.org[Maven^] for projects build and configuration. All the platform artifacts are published in the *Maven Central Repository*, so there is no need to explicitly declare additional repositories in your project `pom` file.

At the top of each _section_ of this documentation you will find the Maven _coordinates_ (group id, artifact id and version) to obtain the artifact(s) as a dependency for your project.

A *BOM (Bill Of Materials)* `pom` is provided to import the available dependencies for a specific version in your projects. The Maven coordinates for the core BOM are the following:

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jdbc</groupId>
<artifactId>holon-jdbc-bom</artifactId>
<version>{revnumber}</version>
----

The BOM can be imported in a Maven project in the following way:

[source, xml, subs="verbatim,quotes,attributes+"]
----
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>com.holon-platform.jdbc</groupId>
			<artifactId>holon-jdbc-bom</artifactId>
			<version>{revnumber}</version>
			*<type>pom</type>*
			*<scope>import</scope>*
		</dependency>
	</dependencies>
</dependencyManagement>
----

=== Using the Platform BOM

The Holon Platform provides an *overall Maven BOM (Bill of Materials)* to easily obtain all the available platform artifacts.

See link:index.html#obtain-the-platform-artifacts[Obtain the platform artifacts] for details.

// Inclusions

include::_datasource.adoc[]

include::_multitenant.adoc[]

include::_spring.adoc[]

== Loggers

By default, the Holon platform uses the https://www.slf4j.org[SLF4J^] API for logging. The use of SLF4J is optional: it is enabled when the presence of SLF4J is detected in the classpath. Otherwise, logging will fall back to JUL (`java.util.logging`).

The logger name for the *JDBC* module is `com.holonplatform.jdbc`.

== System requirements

=== Java

The Holon Platform JDBC module requires https://www.java.com[Java] *8* or higher.

